name:                c4f
version:             0.1.0.0
github:              "MattWindsor91/c4f"
license:             MIT
author:              "Matt Windsor"
maintainer:          "m.windsor@imperial.ac.uk"
copyright:           "2020 Matt Windsor"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/MattWindsor91/c4f#readme>

dependencies:
- base >= 4.7 && < 5
- bytestring >= 0.10.10.1 && < 0.11
- hedgehog >= 1.0.3 && < 2
- lens >= 4.18.1 && < 5
- recursion-schemes >= 5.1.3 && < 6

library:
  source-dirs: src

executables:
  c4f-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - c4f

tests:
  c4f-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - c4f
